server:
  port: 18086

spring:
  application:
    name: gmall-seach
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.211.1:8848
  elasticsearch:
    rest:
      uris: 192.168.211.128:9200



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

