server:
  port: 8888


spring:
  application:
    name: gmall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.211.1:8848


    gateway:
      routes:
        - id: pms-router
          uri: lb://gmall-pms
          predicates:
            - Path=/pms/**
        - id: oms-router
          uri: lb://gmall-oms
          predicates:
            - Path=/oms/**
        - id: sms-router
          uri: lb://gmall-sms
          predicates:
            - Path=/sms/**
        - id: wms-router
          uri: lb://gmall-wms
          predicates:
            - Path=/wms/**
        - id: ums-router
          uri: lb://gmall-ums
          predicates:
            - Path=/ums/**
        - id: index-router
          uri: lb://gmall-index
          predicates:
            - Path=/index/**
        - id: item-router
          uri: lb://gmall-item
          predicates:
            - Host=item.gmall.com
          filters:
            - Auth=/hha,/hha2,/hha3
        - id: auth-router
          uri: lb://gmall-author
          predicates:
            - Host=sso.gmall.com
        - id: cart-router
          uri: lb://gmall-cart
          predicates:
            - Host=cart.gmall.com






jwt:
  pubKeyPath: F:\rsa\rsa.pub
  priKeyPath: F:\rsa\rsa.pri
  secret: 30489ouerweljrLROE@#)(@$*343jlsdf
  cookieName: GMALL-TOKEN
  expire: 180
  unick: unick
