server:
  port: 18081

spring:
  application:
    name: gmall-pms
  datasource:
    username: root
    password: Abcd1234
    url: jdbc:mysql://192.168.211.128:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.211.1:8848

  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 #采样率
  rabbitmq:
    host: 192.168.211.128
    port: 5672
    password: 123456
    username: /xiaofang
    virtual-host: /testVirtual
    publisher-returns: true
    publisher-confirm-type: correlated



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


