server:
  port: 18084

spring:
  application:
    name: gmall-ums
  datasource:
    username: root
    password: Abcd1234
    url: jdbc:mysql://192.168.211.128:3306/guli_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.211.1:8848


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml



aliyun:
  sms:
    accessKeyId: LTAI4G1EJzWWaYAY6Z41AxrS
    accessSecret: ea7Um2iM60Tp2Lh5vUY2Z78MigZHK0
    TemplateCode: SMS_205885637
    SignName: 美年健康
