server:
  port: 18084

spring:
  application:
    name: gmall-ums
  datasource:
    username: root
    password: Abcd1234
    url: jdbc:mysql://192.168.211.128:3306/guli_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.211.1:8848


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

